apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app
  namespace: hotel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app
  template:
    metadata:
      labels:
        app: hotel-app
    spec:
      containers:
        - name: hotel-app
          image: atakowiec/laravel-hotel-app:uniwersalna
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_HOST
              value: "hotel-database"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
